// Code generated by goctl. DO NOT EDIT.
package types

type EchoReq struct {
}

type LoginReply struct {
	Token string `json:"token"`
}

type LoginReq struct {
	Email string `json:"email"`
	Pwd   string `json:"password"`
}

type Response struct {
	Message string `json:"message"`
}
