// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "github.com/wlevene/loginservice/internal/handler/auth"
	"github.com/wlevene/loginservice/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// EchoHandler
				Method:  http.MethodGet,
				Path:    "/echo",
				Handler: EchoHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/auth"),
	)
}
